#!/bin/sh
#
# DANGER!! DON´T CHANGE THIS FILE!!!!
#
# chkconfig:   - 85 15

# Include here all your servers script to load when the server boot

sh /home/deploy/puma_servers/servers.d/leo.com.br.config start > /var/tmp/script.out
